source 'https://github.com/CocoaPods/Specs.git'
source ‘http://bj.gitlab.cnlive.com/ios-team/CNLiveRepos.git’
use_frameworks!

platform :ios, '9.0'

target 'CNLivePublishContent_Example' do
  pod 'CNLivePublishContent', :path => '../'
    pod 'CNLiveTripartiteManagement/QMUIKit'
    pod 'CNLiveTripartiteManagement/Masonry'
    pod 'CNLiveBaseKit'
    pod 'CNLiveTripartiteManagement/MJExtension'
    pod 'CNLiveCustomUI/CNLiveBasicsUI'
    pod 'CNLiveCommonCategory'
    pod 'CNLiveTripartiteManagement/YYKit'
    pod 'CNLiveTripartiteManagement/SDWebImage'
    pod 'CNLiveImagePickerController'
    pod 'CNLiveSDKs', '~> 0.3.0.1'
    pod 'CNLiveCommonClass'
    pod 'CNLiveUserManagement'
    pod 'CNLiveBaseTools'
    pod 'CNLiveAVCamera'
    pod 'CNLiveImagePickerController'
    pod 'CNLiveRequestBastKit'
    pod 'CNLiveEnvironmentConfiguration'
    # pod 'CNLiveUploadManager'
    #依赖三方私有库,如果里面有.a的时候加上这个
    pre_install do |installer| Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    end
  target 'CNLivePublishContent_Tests' do
    inherit! :search_paths
    pod 'CNLiveTripartiteManagement/QMUIKit'
    pod 'CNLiveTripartiteManagement/Masonry'
    pod 'CNLiveBaseKit'
    pod 'CNLiveTripartiteManagement/MJExtension'
    pod 'CNLiveCustomUI/CNLiveBasicsUI'
    pod 'CNLiveCommonCategory'
    pod 'CNLiveTripartiteManagement/YYKit'
    pod 'CNLiveTripartiteManagement/SDWebImage'
    pod 'CNLiveImagePickerController'
    pod 'CNLiveSDKs', '~> 0.3.0.1'
    pod 'CNLiveCommonClass'
    pod 'CNLiveUserManagement'
    pod 'CNLiveBaseTools'
    pod 'CNLiveAVCamera'
    pod 'CNLiveImagePickerController'
    pod 'CNLiveRequestBastKit'
    pod 'CNLiveEnvironmentConfiguration'
    #pod 'CNLiveUploadManager'
    # 依赖三方私有库,如果里面有.a的时候加上这个
    pre_install do |installer| Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    end
  end
end
